# Credit Card Default

https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients

Attribute Information:

This research employed a binary variable, default payment (Yes = 1, No = 0), as the response variable. This study reviewed the literature and used the following 23 variables as explanatory variables: 

* X1: Amount of the given credit (NT dollar): it includes both the individual consumer credit and his/her family (supplementary) credit. 
* X2: Gender (1 = male; 2 = female). 
* X3: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others). 
* X4: Marital status (1 = married; 2 = single; 3 = others). 
* X5: Age (year). 


* X6 - X11: History of past payment. We tracked the past monthly payment records (from April to September, 2005) as follows: 
* X6 = the repayment status in September, 2005; 
* X7 = the repayment status in August, 2005; . . .;
* X11 = the repayment status in April, 2005. 
* The measurement scale for the repayment status is: 
    * -1 = pay duly; 
    * 1 = payment delay for one month; 
    * 2 = payment delay for two months; . . .; 
    * 8 = payment delay for eight months; 
    * 9 = payment delay for nine months and above. 


* X12-X17: Amount of bill statement (NT dollar). 
* X12 = amount of bill statement in September, 2005; 
* X13 = amount of bill statement in August, 2005; . . .; 
* X17 = amount of bill statement in April, 2005. 


* X18-X23: Amount of previous payment (NT dollar). 
* X18 = amount paid in September, 2005; 
* X19 = amount paid in August, 2005; . . .;
* X23 = amount paid in April, 2005. 



In [1]:
import pandas as pd
import numpy as np

In [2]:
!pip install xlrd

     |████████████████████████████████| 96 kB 7.1 MB/s             


In [3]:
df = pd.read_excel("default of credit card clients.xls", skiprows=1)
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0                           1  
1      1000         0      2000                           1  
2      1000      1000      5000                           0  
3      1100      1069      1000                           0  
4      9000       689       679                           0  

[5 rows x 25 columns]

In [4]:
from IPython.display import HTML

In [5]:
pd.set_option('display.max_colwidth', -1)
display(HTML(df.head().to_html()))
pd.reset_option('display.max_colwidth')

/var/folders/rz/yqgs2rws55qdvk0p7vtkrr5m0000gn/T/ipykernel_59882/813028413.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)


In [6]:
list(df.columns)

['ID',
 'LIMIT_BAL',
 'SEX',
 'EDUCATION',
 'MARRIAGE',
 'AGE',
 'PAY_0',
 'PAY_2',
 'PAY_3',
 'PAY_4',
 'PAY_5',
 'PAY_6',
 'BILL_AMT1',
 'BILL_AMT2',
 'BILL_AMT3',
 'BILL_AMT4',
 'BILL_AMT5',
 'BILL_AMT6',
 'PAY_AMT1',
 'PAY_AMT2',
 'PAY_AMT3',
 'PAY_AMT4',
 'PAY_AMT5',
 'PAY_AMT6',
 'default payment next month']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_A

# Gender

Convert gender to 0, 1 instead of 1, 2

In [8]:
df["SEX"] = df["SEX"] - 1.

In [9]:
df["SEX"].value_counts()

1.0    18112
0.0    11888
Name: SEX, dtype: int64

# Education

One Hot Encoding

In [10]:
df["EDUCATION"].value_counts()

2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: EDUCATION, dtype: int64

## 1. Using Keras Utilities

In [30]:
!conda install -y absl-py protobuf wrapt opt_einsum gast astunparse termcolor keras-preprocessing

Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/tensorflow

  added / updated specs:
    - absl-py
    - astunparse
    - gast
    - keras-preprocessing
    - opt_einsum
    - protobuf
    - termcolor
    - wrapt


The following NEW packages will be INSTALLED:

  keras-preprocessi~ conda-forge/noarch::keras-preprocessing-1.1.2-pyhd8ed1ab_0


Preparing transaction: done
Verifying transaction: done
Executing transaction: done


In [31]:
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import preprocessing as keras_processing
encoded = to_categorical(df["EDUCATION"])
print(encoded[:10])

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [32]:
df["EDUCATION"].head(10)

0    2
1    2
2    2
3    2
4    2
5    1
6    1
7    2
8    3
9    3
Name: EDUCATION, dtype: int64

## 2. Alternative Method

In [33]:
unique_edu = df["EDUCATION"].unique()
unique_edu

array([2, 1, 3, 5, 4, 6, 0])

In [34]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
unique_edu = unique_edu.reshape(len(unique_edu), 1)
onehot_encoded = onehot_encoder.fit_transform(unique_edu)

In [35]:
print(onehot_encoded)

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0.]]


# Marriage

In [36]:
df["MARRIAGE"] = df["MARRIAGE"] - 1.0

In [37]:
df["MARRIAGE"].value_counts()

 1.0    15964
 0.0    13659
 2.0      323
-1.0       54
Name: MARRIAGE, dtype: int64

We need to decide what to do with 0 and -1. 

1 and 2 are male; 2 = female respectively

We will convert -1 to 0. 

In [38]:
df["MARRIAGE"].iloc[np.where(df["MARRIAGE"] == -1.0)] = 0

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


# Age

In [39]:
df["AGE"].value_counts()

29    1605
27    1477
28    1409
30    1395
26    1256
31    1217
25    1186
34    1162
32    1158
33    1146
24    1127
35    1113
36    1108
37    1041
39     954
38     944
23     931
40     870
41     824
42     794
44     700
43     670
45     617
46     570
22     560
47     501
48     466
49     452
50     411
51     340
53     325
52     304
54     247
55     209
56     178
58     122
57     122
59      83
60      67
21      67
61      56
62      44
63      31
64      31
66      25
65      24
67      16
69      15
70      10
68       5
73       4
72       3
75       3
71       3
79       1
74       1
Name: AGE, dtype: int64

A question we should ask ourselves is should we bin our data?

Let's try without binning for now

# PAY_0, ... PAY_06

In [40]:
df["PAY_0"].value_counts()

 0    14737
-1     5686
 1     3688
-2     2759
 2     2667
 3      322
 4       76
 5       26
 8       19
 6       11
 7        9
Name: PAY_0, dtype: int64

# Bill Statement

X12-X17: Amount of bill statement (NT dollar).

X12 = amount of bill statement in September, 2005;

X13 = amount of bill statement in August, 2005; . . .;

X17 = amount of bill statement in April, 2005.


In [41]:
df["BILL_AMT1"].value_counts()

0         2008
390        244
780         76
326         72
316         63
          ... 
11636        1
146034       1
20817        1
1351         1
47929        1
Name: BILL_AMT1, Length: 22723, dtype: int64

# Previous Payment

X18-X23: Amount of previous payment (NT dollar).

X18 = amount paid in September, 2005;

X19 = amount paid in August, 2005; . . .;

X23 = amount paid in April, 2005.

In [42]:
df["PAY_AMT1"].value_counts()

0        5249
2000     1363
3000      891
5000      698
1500      507
         ... 
3391        1
7785        1
66022       1
10121       1
85900       1
Name: PAY_AMT1, Length: 7943, dtype: int64

There are a few things we need to pay attention to here. 

We ought to ask ourselves. Is raw bill statement amount important? This informs us how much is owed. How do we tell if this is significant. Of course, it is related to their assets and income. However, we lacked those information.

Let's example previous payment. What kind of assumptions or hypothesis can we make initially. Payment is important. Amount repaid is also important. Do we need to engineer some features? Say relate payment with the amount owed?

Do we combine the credit card limit with bill amount. I.e., is the amount he owe close to the limit of his credit card balance? Does it matter? A simple feature we can engineer may be to divide the amount billed with the credit card limit.

# Model

Let's start with some simple model. Logistic regression. 




In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [44]:
features = pd.concat([df[['LIMIT_BAL', 'SEX', 'AGE', 'EDUCATION',
                          'PAY_0', 'PAY_2', 'PAY_3', 
                          'PAY_4', 'PAY_5', 'PAY_6',
                          'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 
                          'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6',
                          'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
                          'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']], pd.DataFrame(encoded)], axis=1)
features.head()

LIMIT_BAL  SEX  AGE  EDUCATION  PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  \
0      20000  1.0   24          2      2      2     -1     -1     -2     -2   
1     120000  1.0   26          2     -1      2      0      0      0      2   
2      90000  1.0   34          2      0      0      0      0      0      0   
3      50000  1.0   37          2      0      0      0      0      0      0   
4      50000  0.0   57          2     -1      0     -1      0      0      0   

   ...  PAY_AMT4  PAY_AMT5  PAY_AMT6    0    1    2    3    4    5    6  
0  ...         0         0         0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
1  ...      1000         0      2000  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
2  ...      1000      1000      5000  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
3  ...      1100      1069      1000  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
4  ...      9000       689       679  0.0  0.0  1.0  0.0  0.0  0.0  0.0  

[5 rows x 29 columns]

In [45]:
n = 25000

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score

## Model 1:

In [47]:
clf = LogisticRegression()

In [48]:
clf.fit(features[:n], df["default payment next month"].values[:n])
y_train_pred = clf.predict(features[:n])
y_test_pred = clf.predict(features[n:])

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names t

## Train

In [49]:
print(confusion_matrix(df["default payment next month"].values[:n], 
                       y_train_pred))
print(accuracy_score(df["default payment next month"].values[:n],
                     y_train_pred))

[[19416     6]
 [ 5574     4]]
0.7768


## Test

In [50]:
print(confusion_matrix(df["default payment next month"].values[n:], 
                       y_test_pred))
print(accuracy_score(df["default payment next month"].values[n:],
                     y_test_pred))

[[3939    3]
 [1058    0]]
0.7878


## Model 2:

In [51]:
clf = RandomForestClassifier(random_state=42)

In [52]:
clf.fit(features[:n], df["default payment next month"].values[:n])
y_train_pred = clf.predict(features[:n])
y_test_pred = clf.predict(features[n:])

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


## Train

In [53]:
print(confusion_matrix(df["default payment next month"].values[:n], 
                       y_train_pred))
print(accuracy_score(df["default payment next month"].values[:n],
                     y_train_pred))

[[19411    11]
 [   12  5566]]
0.99908


## Test

In [54]:
print(confusion_matrix(df["default payment next month"].values[n:], 
                       y_test_pred))
print(accuracy_score(df["default payment next month"].values[n:],
                     y_test_pred))

[[3759  183]
 [ 677  381]]
0.828


***